[pytest]
testpaths = tests
addopts =
    --tb=short
    -q
    --cov=src
    --cov-report=term-missing
    --cov-report=html:docs/coverage
filterwarnings =
    ignore::DeprecationWarning:nibabel
    ignore::DeprecationWarning:pydicom